# Database Configuration
# Render's DATABASE_URL needs jdbc:postgresql:// prefix and often sslmode=require
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/job_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mysql212003}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Force PostgreSQL dialect for cloud
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Port Configuration
server.port=${PORT:8080}

# Optimization for faster startup
spring.main.banner-mode=off
logging.level.org.springframework.web=DEBUG
